name: Build, Push & Deploy to Phala TEE

on:
  push:
    branches:
      - main
    paths:
      - "api-server/pyproject.toml"
      - "api-server/Dockerfile"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

env:
  APP_NAME: ${{ vars.APP_NAME || secrets.APP_NAME }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME || secrets.DOCKER_USERNAME }}
  DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE || secrets.DOCKER_IMAGE }}
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || secrets.DOCKER_REGISTRY || 'docker.io' }}
  DOCKER_REGISTRY_USERNAME: ${{ vars.DOCKER_REGISTRY_USERNAME || secrets.DOCKER_REGISTRY_USERNAME }}
  DOCKER_REGISTRY_PASSWORD: ${{ vars.DOCKER_REGISTRY_PASSWORD || secrets.DOCKER_REGISTRY_PASSWORD }}
  PHALA_CLOUD_API_KEY: ${{ vars.PHALA_CLOUD_API_KEY || secrets.PHALA_CLOUD_API_KEY }}

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_REGISTRY_USERNAME }}
          password: ${{ env.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: api-server
          file: api-server/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Install Tee Cloud CLI
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          export PATH="$HOME/.bun/bin:$PATH"
          git clone https://github.com/Phala-Network/tee-cloud-cli.git
          cd tee-cloud-cli
          bun install
          bun run build
          sudo ln -s "$(pwd)/dist/index.js" /usr/local/bin/teecloud
          cd ..

      # Configure Phala Cloud API key
      - name: Configure Phala Cloud
        run: |
          teecloud set-apikey ${{ env.PHALA_CLOUD_API_KEY }}
          echo "Verifying Phala Cloud access..."
          teecloud list-cvms

      - name: Update Docker Compose
        run: |
          sed -i "s|\${DOCKER_IMAGE}|${DOCKER_IMAGE}|g" ./api-server/docker-compose.yml

      - name: Deploy to Phala Cloud
        run: |
          cat api-server/docker-compose.yml
          teecloud deploy \
            -n ${{ env.APP_NAME }} \
            -c api-server/docker-compose.yml \
            -t phala \
            -m docker-compose